Default: &defaults
  database: Gacha.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: Gacha_test.sqlite3
  <<: *defaults

Staging:
  database: Gacha_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: Gacha_production.sqlite3
  poolsize: 100
  <<: *defaults
